### ISSUE TITLE
Ending Scene (Content)

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/desire#20]
**Beats:**
-Click onto the boat
-Screeching sound of ship sinking
-Soundtrack starting with fadein 5.0
-Black screen fade.
-Text appears in black screen: I made it just in time. Now I need to get to the shore.
-BG appears
-BG effect of moving forward activates like the one I made here https://youtu.be/2fAl-pQqjLo?t=80 that gives you the illusion that you're moving. 
-Black screen fade.
-Text appears in black screen: The Promised Land... It should be somewhere near here.
-BG with led appears.
-BG effect of moving forward.
-Led's master appears with transition (only him), we don't need a black fade.
-Text appears above Led's head: Master? 
-Rolling Credits start after a while (like 2 secs).

**Comment by alexitsios** [comment]
@josschi95 can you enhance the ending scene with the above beats? Let me know if you need further clarification.

**Comment by DerekGooding** [comment]
I didn't update the outro but I did correct the scrolling at the end. I think it's polished enough to publish so I'm closing the issue.
