### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/desire#21]
Finish the translation to Brazilian Portuguese

**Comment by alexitsios** [comment]
@vitormaduro if the portogues version isn't ready yet, I suggest we release with the English one first. If that's the case, we should remove the option for language for now.

**Comment by alexitsios** [comment]
@josschi95 can you remove this field since we won't be having a second translation for the game for now?

**Comment by josschi95** [comment]
Included in most recent pull request. For now I just disabled the language dropdown element in the Settings UI panel
