### ISSUE TITLE
Screeching sound

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/desire#22]
[rumble-fade-out-10s-85243.zip](https://github.com/alexitsios/desire/files/10445849/rumble-fade-out-10s-85243.zip)

Place the following quaking sound in the following locations:

1. When you return from the funnel with the all in one toolkit.
2. When you enter the bridge.
3. When you take the boat. We could have a short 2-3 second shake there along with the sound, then the fade to black screen.

**Comment by alexitsios** [comment]
@vitormaduro I added you in this ticket as well since you're also handling the narrative aspect. Let me know if you can handle this, so that we give space to @DerekGooding to do more crucial bugs. Thank you!

**Comment by alexitsios** [comment]
@josschi95 can you go ahead and take over this task?

**Comment by josschi95** [comment]
Added sound. The file given is super quiet though, and not really a "screech"

**Comment by alexitsios** [comment]
I know it's not a creaking /screeching sound, but it's the best I could find.

**Comment by alexitsios** [comment]
@DerekGooding can you check if the sound plays? It's as if it doesn't @josschi95 mentioned something about the volume being too low for this asset.
